version: 2.1

setup: true

orbs: 
  continuation: circleci/continuation@0.3.1

jobs:
  generate-merged-yaml:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "merge YAML"
          command: |
            "yq eval-all '. as $item ireduce ({}; . * $item )' ./ios/circleci.yml ./android/circleci.yml > merged.yml"
      - run:
          name: "cat merged.yml"
          command: "cat merged.yml"
      - continuation/continue:

          configuration_path: "merged.yml"

workflows:
  setup-workflow:
    jobs:
      - generate-merged-yaml
