version: 2.1

jobs:
  android-job:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "cat hoge.txt"
          command: cat ./android/hoge.txt

workflows:
  run-android-job:
    jobs:
      - android-job