version: 2.1

orbs:
  path-filtering: circleci/path-filtering@0.1.3

jobs:
  android-job:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "cat hoge.txt"
          command: cat ./android/hoge.txt

workflows:
  run-android-job:
    jobs:
      - path-filtering/filter:
        config-path: merged.yml
        mapping: ./android/.* true
      - android-job