version: 2.1

jobs:
  ios-job:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "cat hoge.txt"
          command: cat ./ios/hoge.txt

workflows:
  run-ios-job:
    jobs:
      - ios-job