version: 2.1

jobs:
  say-hello-ios:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo iOS!"

workflows:
  say-hello-ios-workflow:
    jobs:
      - say-hello-ios