version: 2.1

jobs:
  echo-hoge:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Run Test"
          command: echo << pipeline.parameters.hoge >>
    
parameters:
  hoge:
    type: boolean
    default: true

workflows:
  run_hoge:
    jobs:
      - echo-hoge