version: 2.1

parameters:
  run-ios-workflow:
    type: boolean
    default: false

jobs:
  ios-job:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: "echo iOS!"

workflows:
  ios-workflow:
    when: << pipeline.parameters.run-ios-workflow >>
    jobs:
      - ios-job